#! /bin/sh
case "$1" in 
    start)
        echo "Starting sockerserver"
        start-stop-daemon -S -a aesdsocket -x /usr/bin/aesdsocket -- -d

        ;;
    stop)
        echo "Stoping aesdsocket"
        pkill -f aesdsocket
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
exit 0