#! /bin/sh
case "$1" in 
    start)
        echo "Starting sockerserver"
        start-stop-daemon -S aesdsocket /usr/bin/aesdsocket -d
        ;;
    stop)
        echo "Stoping aesdsocket"
        start-stop-daemon -K aesdsocket
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
exit 0